# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021 Semidrive Electronics Co., Ltd.
#

obj-$(CONFIG_SEMIDRIVE_COMMON) += board-common.o board-info.o
obj-$(CONFIG_SYSCOUNTER_TIMER) += syscounter.o

obj-$(CONFIG_SEMIDRIVE_D9_SERIES) += d9/
